# Generated by Django 5.0 on 2023-12-20 16:30

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Todos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 20, 17, 30, 37, 58449),
                verbose_name="Created",
            ),
        ),
        migrations.AddField(
            model_name="todo",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="todo",
            name="iscompleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="todo",
            name="title",
            field=models.CharField(default="Enter your title", max_length=200),
        ),
        migrations.AddField(
            model_name="todo",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 20, 17, 30, 37, 58449),
                verbose_name="Update",
            ),
        ),
        migrations.AddField(
            model_name="todo",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
