# Generated by Django 5.0 on 2023-12-20 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Todos", "0002_todo_created_at_todo_description_todo_iscompleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 20, 17, 38, 54, 498890),
                verbose_name="Created",
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 20, 17, 38, 54, 498890),
                verbose_name="Update",
            ),
        ),
    ]
