# Generated by Django 5.0 on 2023-12-20 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Todos", "0003_alter_todo_created_at_alter_todo_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="iscompleted",
            new_name="completed",
        ),
        migrations.AlterField(
            model_name="todo",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 20, 18, 9, 25, 36424),
                verbose_name="Created",
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 20, 18, 9, 25, 36424),
                verbose_name="Updated",
            ),
        ),
    ]
