# Generated by Django 5.0 on 2023-12-20 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Todos", "0004_rename_iscompleted_todo_completed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 20, 18, 10, 48, 388852),
                verbose_name="Created",
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 20, 18, 10, 48, 388852),
                verbose_name="Updated",
            ),
        ),
    ]
