# Generated by Django 5.0 on 2023-12-20 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Todos", "0006_alter_todo_created_at_alter_todo_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="completed",
        ),
        migrations.AlterField(
            model_name="todo",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 20, 18, 13, 8, 604094),
                verbose_name="Created",
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 20, 18, 13, 8, 604094),
                verbose_name="Updated",
            ),
        ),
    ]
